---
title: 'Research Recommendations'
author: "Leah Thornton Hampton"
date: "8/2/2021"
output:
  html_document: 
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float: true
---

# Data Import and Tidying

```{r Data Import and Packages, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}

#Import packages
library(tidyverse)
library(collapsibleTree) #plot type for endpoint category tree
library(calecopal) #colors 
library(wesanderson) #colors

#Import Data
aoc <- read_csv("AquaticOrganisms_Clean_final.csv", guess_max = 10000)

```

```{r}

size_histogram <- aoc %>% 
  group_by(article, size.length.um.used.for.conversions) %>% 
  summarise()

histogram <- size_histogram %>% 
  ggplot(aes(x = size.length.um.used.for.conversions)) +
  geom_histogram(bins = 50) +
  geom_vline(xintercept = c(1, 10, 100, 1000))+
  scale_x_log10() +
  labs(x = "Size (microns)", y = "Number of Studies")

plot(histogram)

```

```{r}

virgin_summary <- aoc %>% 
  group_by(article, weather.biofoul) %>% 
  summarise() %>%
  filter(weather.biofoul == "Y")
  
```

```{r}

morphology_summary <- aoc %>% 
  group_by(article, shape) %>% 
  summarise() %>% 
  drop_na() %>% 
  ungroup() %>% 
  count(shape == "sphere") %>%
  mutate(shape_prop = prop.table(n))  

morphology_summary <- aoc %>% 
  group_by(article, shape) %>% 
  summarise() %>% 
  drop_na() %>% 
  ungroup() %>% 
  count(shape == "fiber") %>%
  mutate(shape_prop = prop.table(n)) 

morphology_summary <- aoc %>% 
  group_by(article, shape) %>% 
  summarise() %>% 
  drop_na() %>% 
  ungroup() %>% 
  count(shape == "fragment") %>%
  mutate(shape_prop = prop.table(n)) 

```

