---
title: "Confidence Voting Figures"
author: "Scott Coffin"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(reshape2)
```

```{r}
votes <- read_excel("Threshold_Manuscript_Figures/voting_ambient.xlsx", sheet  ="Tidy") %>% 
  mutate(Value = as.numeric(Value)) %>% 
  mutate_if(is.character,as.factor)
```

```{r}
library(ggplot2) 
library(grid)
library(RColorBrewer)

make_gradient <- function(deg = 45, n = 100, cols = blues9) {
  cols <- colorRampPalette(cols)(n + 1)
  rad <- deg / (180 / pi)
  mat <- matrix(
    data = rep(seq(0, 1, length.out = n) * cos(rad), n),
    byrow = TRUE,
    ncol = n
  ) +
  matrix(
    data = rep(seq(0, 1, length.out = n) * sin(rad), n),
    byrow = FALSE,
    ncol = n
  )
  mat <- mat - min(mat)
  mat <- mat / max(mat)
  mat <- 1 + mat * n
  mat <- matrix(data = cols[round(mat)], ncol = n)
  grid::rasterGrob(
    image = mat,
    width = unit(1, "npc"),
    height = unit(1, "npc"), 
    interpolate = TRUE
  )
}
```

#prep
```{r}
#get data in wide format
cast <- votes %>% 
  #rowid_to_column(var = "rowid") %>% 
  #dcast(Threshold + ERM + Round + Person ~  Confidence.Type, value.var = "Value")
  dcast(... ~ Confidence.Type, value.var = "Value")
  

final <- cast %>% group_by(Person, Threshold, Round, ERM) %>%
    summarise(Confidence = sum(Confidence, na.rm = T),
    `Level of Agreement` = sum(`Level of Agreement`, na.rm = T), 
    `Weight of evidence` = sum(`Weight of evidence`, na.rm = T)) %>% 
  na_if(0)

### Repeat for confidence in threshold approach
#get data in wide format
approach <- votes %>% 
  filter(ERM == "overall") %>% 
  #rowid_to_column(var = "rowid") %>% 
  #dcast(Threshold + ERM + Round + Person ~  Confidence.Type, value.var = "Value")
  dcast(... ~ Threshold, value.var = "Value")
```

#Plot
```{r}
g <- make_gradient(
  deg = 135, n = 500, cols = rev(brewer.pal(5, "Spectral"))
)

#make plot
final %>% 
  group_by(Threshold, Round, ERM) %>% 
  summarize(mean.agreement = mean(`Level of Agreement`, na.rm = TRUE),
            sd.agreement = sd(`Level of Agreement`, na.rm = TRUE),
            mean.weight = mean(`Weight of evidence`, na.rm = TRUE),
            sd.weight = sd(`Weight of evidence`, na.rm = TRUE)) %>% 
  filter(ERM != "overall") %>% 
 # filter(Round == "Round 2") %>% 
         #Threshold == "Threshold 1") %>% 
  ggplot(aes(y = mean.agreement, x = mean.weight, color = Round)) +
  #make backgroud first
  annotation_custom(
    grob = g, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  ) +
  #layer points on top
  geom_point() +
  scale_color_manual(name = "Voting Round",
                       values = c("gray1", "gray80"),
                     labels = c("Round 2", "Round 1")) +
  # add error bars
  geom_pointrange(aes(ymin = mean.agreement - sd.agreement, ymax = mean.agreement + sd.agreement)) +
  geom_errorbarh(aes(xmin = mean.weight - sd.weight, xmax = mean.weight + sd.weight)) +
  #give range
  scale_x_continuous(limits = c(1,5),
                     breaks = 1:5,
                     labels = c("Very low", "Low", "Medium", "High", "Very high")) +
  scale_y_continuous(limits = c(1,5),
                     breaks = 1:5,
                     labels = c("Very low", "Low", "Medium", "High", "Very high")) +
 # scale_x_discrete(breaks = 1:3, labels = c("Very low", "Medium", "Very high")) +
  #labels
  labs(title = "Ambient Microplastics Framework Confidence Voting",
       subtitle = "Mean +- s.d. (n = 11)",
         x = "Weight of Evidence",
       y = "Level of Agreement in the outcome among studies") +
theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5)) +
  facet_grid(Threshold ~ ERM)#,
             #nrow = 4)
```
```{r}
approach %>% 
  group_by(Round) %>% 
  summarize(mean.analytical = mean(`Anlaytical Process`, na.rm = TRUE),
            sd.analytical = sd(`Anlaytical Process`, na.rm = TRUE),
            mean.Framework = mean(`Framework`, na.rm = TRUE),
            sd.Framework = sd(`Framework`, na.rm = TRUE)) %>% 
 # filter(Round == "Round 2") %>% 
         #Threshold == "Threshold 1") %>% 
  ggplot(aes(y = mean.analytical, x = mean.Framework, color = Round)) +
  #make backgroud first
  annotation_custom(
    grob = g, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  ) +
  #layer points on top
  geom_point() +
  scale_color_manual(name = "Voting Round",
                       values = c("gray10", "gray80"),
                     labels = c("Round 2", "Round 1")) +
  # add error bars
  geom_pointrange(aes(ymin = mean.analytical - sd.analytical, ymax = mean.analytical + sd.analytical)) +
  geom_errorbarh(aes(xmin = mean.Framework - sd.Framework, xmax = mean.Framework + sd.Framework)) +
  #give range
  coord_cartesian(ylim = c(1,5),
                  xlim = c(1,5)) +
  scale_x_continuous(
                     breaks = 1:5,
                     labels = c("Very low", "Low", "Medium", "High", "Very high")) +
  scale_y_continuous(
                     breaks = 1:5,
                     labels = c("Very low", "Low", "Medium", "High", "Very high")) +
 # scale_x_discrete(breaks = 1:3, labels = c("Very low", "Medium", "Very high")) +
  #labels
  labs(title = "Ambient Microplastics Framework Confidence Voting",
       subtitle = "Mean +- s.d. (n = 11)",
         x = "Confidence in Analytical Process",
       y = "Confidence in Framework") +
theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5))
```

