---
title: "Global Microplastics Risk Characterization"
author: "Scott Coffin"
date: "3/10/2021"
output:   
  html_document:
    code_folding: hide
    theme: journal
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: true
    includes:
     # after_body: footer.html
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      warning=FALSE, message=FALSE,time_it = TRUE) #report
```

```{r}
library(tidyverse)
library(calecopal)
library(ssdtools)
library(DT)
library(plotly)
library(gridExtra)
library(grid)
library(wesanderson)
library(ggdark)
library(broom)
library(knitr)
```

# Hazard Concentration and Alignment Parameters
```{r}
# Choose hazard concentration and confidence intervals
#particles/L
Threshold1 = 0.18 #90000 
Threshold2 = 0.38 #383000
Threshold3 = 0.37 #391000
Threshold4 = 2.08 #1e6

kable(data.frame(
  Category = c("Hazard Concentrations (particles/L)"),
  "Threshold1" = Threshold1,
  "Threshold 2" = Threshold2,
  "Threshold 3" = Threshold3,
  "Threshold 4" = Threshold4))
```

```{r}
# Choose concentration alignment parameters
alpha = 2.5 #(use 1.6 or 2.5)
x2D_set = 5000#100 #upper size range (microns)
x1D_set = 1#1 #lower size range (microns)

kable(data.frame(
  Category = c("Concentration Alignment Parameters"),
  alpha = alpha,
  "lower_size_range_microns" = x1D_set,
  "upper_size_range_microns" = x2D_set))
```

```{r}
#data import
# Adam et al (2019) data needs correcting
adam <- read.csv("Risk Characterization/datasets/adam2019.csv", na.strings = "N.A.", fileEncoding="UTF-8-BOM") %>% 
  mutate(x1M = Min.particle.size.um,
         x2M = Max.particle.size.um) %>% 
  mutate(Sample.Type = "sample")

#SF bay data from Zhu et al (2021)
sfBay <- read.csv("Risk Characterization/datasets/SFBayData.csv", na.strings = "NA", fileEncoding="UTF-8-BOM", stringsAsFactors = TRUE) %>% 
  rename(x1M = Min.particle.size.um,
         x2M = Max.particle.size.um) %>% 
  mutate(Sample.Type = "sample")
```

```{r}
# Align Data

#function to derive correction factor (CF) from Koelmans et al (equation 2)
CFfnx = function(a = alpha, #default alpha from Koelmans et al (2020)
                 x2D = x2D_set, #set detault values to convert ranges to (1-5,000 um) #5mm is upper defuault 
                 x1D = x1D_set, #1 um is lower default size
                 x2M, x1M){
  
  CF = (x2D^(1-a)-x1D^(1-a))/(x2M^(1-a)-x1M^(1-a))
  
  return(CF)
}
#verify it works (expected answer is 40.37)
#CFfnx(x1M = 333, x2M = 5000)

adam <- adam %>% 
  mutate(CF = CFfnx(x1M = x1M, x2M = x2M)) %>%  #create new column with correction factor 
  mutate(particles.m3.corrected = CF * Single.Measurement.conc....m3.) %>% #convert single concenetrations
  mutate(particles.m3.corrected_mean = CF * Mean.conc....m3.) %>%  #convert mean concentrations from distributions
  mutate(particles.m3.corrected_median = CF * Median.conc....m3.) %>%   #convert mean concentrations from distributions
  mutate(particles.single.median.m3 = ifelse(is.na(particles.m3.corrected), particles.m3.corrected_median, particles.m3.corrected)) %>% 
  mutate(particles.m3.master = ifelse(is.na(particles.single.median.m3), particles.m3.corrected_mean, particles.single.median.m3)) %>% 
  mutate(particle.L.master = particles.m3.master/1000) %>% 
  filter(particle.L.master > 0) %>% 
  mutate(System = factor(System)) %>% 
  mutate(source = "Adam")

# correct aquatic concentrations for SF Bay
sfBay_sub <- sfBay %>% 
  mutate(CF = CFfnx(x1M = x1M, x2M = x2M)) %>%  #create new column with correction factor 
  mutate(particle.L.master = particles.L.blank.corrected * CF) %>% 
  mutate(source = "SFEI") %>% 
  mutate(Reference = "Zhu et. al 2021") %>% 
  rename(Sampling.location = general.location) %>% 
  select(-c(particles.L.blank.corrected, particles.kg.blank.corrected, particles.fish.blank.corrected))

## join datasets ##
#first ensure that both datasets share all columns
adam_sub <- adam %>% 
  select(c(Sampling.apparatus, Sampling.location, x1M, x2M, Sample.Type, System, CF,particle.L.master, source, Reference)) %>% 
  mutate(sampleID = NA,
         specific.location = NA,
         latitude = NA,
         longitude = NA,
         sample.matrix = NA,
         sample.matrix.specific = NA
         )

#join data
globalData <- rbind(adam_sub, sfBay_sub) %>% 
  mutate(Conc = particle.L.master)
```
#Plot

```{r}
#make new dataframe to plot both histograms together
sampleSimpleADAM <- globalData %>%
  dplyr::select(Conc, Sample.Type) %>% 
  droplevels()

#make new dataframe to plot both histograms together
dfADAM <- rbind(sampleSimpleADAM)#,food.dilution.simple)
```

## Exceedances
```{r}
#calculate exceedance
dfADAM_exceedance <- dfADAM %>% 
  mutate(aboveThreshold1 = factor(case_when(
    Conc >= Threshold1 ~ "above Threshold 1",
    Conc < Threshold1 ~ "below Threshold 1",
  )))

#give summary stat for exceedance
exceedance <- dfADAM_exceedance  %>%
  filter(Sample.Type == "sample") %>% 
  dplyr::select(c(Conc, aboveThreshold1)) %>%
  group_by(aboveThreshold1) %>%
  dplyr::summarize(n = n()) %>% 
  mutate(rel.freq = paste0(round(100 * n/sum(n), 0), "%"))

kable(exceedance)
```
## Histogram
```{r}
#generate plot
dfADAM_exceedance %>% 
  filter(Sample.Type == "sample") %>% 
  ggplot(aes(x = Conc, fill = aboveThreshold1))+
  geom_histogram(aes(y = ..count../sum(..count..)),bins = 50, alpha = 0.9, position = "identity") +
  #geom_smooth(stat = 'density') +
  geom_vline(xintercept = Threshold1, linetype = "dashed", color = "red") +
  geom_text(aes(x = Threshold1- 0.5*Threshold1, y = 0.055), label = paste(Threshold1,"particles/L"),  color = "red") +
  geom_text(aes(x = Threshold1- 0.5*Threshold1, y = 0.06), label = ("Threshold1"),  color = "red") +
  geom_text(aes(x = Threshold1+ Threshold1, y = 0.050), label = paste(exceedance$rel.freq[1], "Above Threshold1"), color = "red") +
  scale_x_log10() +
  #coord_cartesian(xlim = c(0,100000000)) +
  # scale_x_continuous(labels = scales::scientific) +
  xlab("Concentration (particles/L)")+
  scale_y_continuous(name = "Relative Density", labels = scales::percent)+
  #scale_fill_discrete(labels = c("Environmental Concentration", "LOEC")) +
  #scale_color_discrete(labels = c("Environmental Concentration", "LOEC")) +
  labs(title = "Histograms of Concentrations in Adam et al 2019 Dataset",
       caption = "Adam et al. 2019 data; all data corrected to 1-5,000 um; nominal particle/L",
       fill = "Env. Conc. or Tox. Conc.",
       color = "Env. Conc. or Tox. Conc.") +
  theme_minimal() +
  theme(legend.position = "none",
    plot.title = element_text(hjust = 0.5, size = 20),
        axis.title = element_text(size = 16),
        axis.text =  element_text(size = 16),
        legend.text = element_text(size =14),
        legend.title = element_blank())
```
## ECDF

```{r}
#ECDF by System
adam %>% 
filter(System != "") %>% 
  ggplot(aes(x = particle.L.master)) + #, color = System))+
  stat_ecdf(geom = "point", size = 1, alpha = 0.7) +
  stat_ecdf(geom = "step", linetype = 'solid', alpha = 0.3, size = 1.5, color = 'azure3') +
  scale_color_manual(values = wes_palette("Darjeeling1"))+
  geom_vline(xintercept = Threshold1, linetype = 'dashed', color = 'green', size = 1.3) +
  geom_vline(xintercept = Threshold2, linetype = 'dashed', color = 'yellow', size = 1.3) +
  geom_vline(xintercept = Threshold3, linetype = 'dashed', color = 	'orange', size = 1.3) +
  geom_vline(xintercept = Threshold4, linetype = 'dashed', color = 	'red', size = 1.3) +
  geom_text(label = "Threshold 1", color = 'green', x = Threshold1, y = 0.15, size = 6)+
  geom_text(label = "Threshold 2", color = 'yellow', x = Threshold2, y = 0.22, size = 6)+
  geom_text(label = "Threshold 3", color = 'orange', x = Threshold3, y = 0.35, size = 6)+
  geom_text(label = "Threshold 4", color = 'red', x = Threshold4, y = 0.45, size = 6)+
  ylab("Cumulative Density") +
  xlab(paste0("Particles/L (" ,x1D_set, " to ", x2D_set, "um)"))+
  scale_y_continuous(labels = scales::percent)+
  coord_trans(x = "log10") +
  scale_x_continuous(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = comma_signif)+
  annotation_logticks(sides = "b")+ #log scale rick marks on bottom
  #theme_minimal() +
  dark_theme_minimal(base_size = 15) +
  labs(title = "Global Surface Water Marine Microplastics Concentrations",
       subtitle = paste("Particles/L corrected to:",x1D_set, "to", x2D_set, "um"),
       caption = paste("Concentration data from Adams et al (2019): 23 studies, 57 sampling locations, n = 377; corrected for size ranges. Alpha = ",alpha))+
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
        plot.subtitle = element_text(hjust = 0.5, size = 14))
```


# Modelling

```{r}
sample_dists_ADAM <- ssd_fit_dists(samplesADAM, #data frame
                              left = "Conc", #string of the column in data with the concentrations
                              # right = left, #string of the column with the right concentration values. If different from left, then the data are considerd to be censored
                              dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), #char vector of distribution anmes
                              computable = FALSE, #flag specifying whether to only return fits with numerically computable standard errors
                              silent = FALSE) #flag indicating whether fits should fail silently

autoplotADAM<- autoplot(sample_dists_ADAM) #plots the distribution in ggplot2
autoplotADAM
ssd_gof(sample_dists_ADAM) #check the goodness of fit
#there are multiple fitting distributions, so check which fits best
sample_gof_ADAM <- ssd_gof(sample_dists_ADAM)
sample_gof_ADAM[order(sample_gof_ADAM$delta), ] #orders by delta. Use the aicc (Akaike's Information Criterion corrected for sample size) for model selection 
write.csv(sample_gof_ADAM,"Concentration data/sample_gof_ADAM.csv")
#choose the distribution that you want to plot
sample_dists_ADAM_choice <- ssd_fit_dists(samplesADAM, #data frame
                                   left = "Conc", #string of the column in data with the concentrations
                                   # right = left, #string of the column with the right concentration values. If different from left, then the data are considerd to be censored
                                   dists = c("lgumbel"), #char vector of distribution anmes
                                   computable = FALSE, #flag specifying whether to only return fits with numerically computable standard errors
                                   silent = FALSE) #flag indicating whether fits should fail silently
set.seed(99)
sample_pred_ADAM <- predict(sample_dists_ADAM_choice,
                       average = FALSE,
                       ic = "aicc",
                       nboot = 10,
                       ci= TRUE) #estimates model-averaged estimates based on aicc

sample_pred_ADAM # The resultant object is a data frame of the estimated concentration (est) with standard error (se) and lower (lcl) and upper (ucl) 95% confidence limits by percent of species affected (percent). The confidence limits are estimated using parametric bootstrapping.

```

```{r}
sample_pred_ADAM %>% mutate_if(is.numeric, ~ signif(., 3)) %>% 
  datatable(rownames = FALSE,
            extensions = c('Buttons', 'Scroller'),
            options = list(
              dom = 'Brftp',
              scrollY = 400,
              scroller = TRUE,
              buttons = c('copy', 'csv', 'excel')), 
            class = "compact",
            colnames = c("Percent", "Estimated Mean Concentration", "Standard Error", "Lower 95% Confidence Limit", "Upper 95% Confidence Limit", "Distribution"),
            caption = "Predicted Concentration distribution with uncertanties."
  )

#order data
samplesADAM <- samplesADAM %>% 
  filter(System != "") #take out blanks

sampleSSDADAM <- samplesADAM[order(samplesADAM$Conc), ]
sampleSSDADAM$frac <- ppoints(samplesADAM$Conc, 0.5)
```


```{r}
ECDF_model_occurrence_ADAM <- ggplot(sample_pred_ADAM,aes_string(x = "est")) +
  geom_xribbon(aes_string(xmin = "lcl", xmax = "ucl", y = "percent/100"), alpha = 0.2, color = "#81a88d", fill = "#81a88d") +
  geom_line(aes_string(y = "percent/100"), linetype = 'dashed', alpha = 0.8) +
  geom_point(data = sampleSSDADAM,aes(x = Conc, y =frac, color = System), size =1) + 
  #geom_text(data = sampleSSD, aes(x = Conc, y = frac, label = Location), hjust = 1.1, size = 4) + #season labels
  scale_y_continuous("Cumulative Distribution (%)", labels = scales::percent) +
  #expand_limits(y = c(0, 1)) +
  xlab("Concentration (particles/L)")+
  labs(title = "Adam et al 2019 Microplastics Concentration Cumulative Distribution Function",
       subtitle = "Smoothing/95% CI ribbon based on average of log-logical and log-normal Distributions Fit",
       caption = "Adam et al 2019 data; sampling corrected to 1-5,000 um") +
  coord_trans(x = "log10") +
  scale_x_continuous(breaks = scales::trans_breaks("log10", function(x) 10^x),labels = comma_signif)+
  scale_color_manual(values = wes_palette("Darjeeling2"))

#white mode
ECDF_model_occurrence_ADAM_white <- ECDF_model_occurrence_ADAM +
  geom_vline(xintercept = Threshold1, linetype = 'dashed', color = 'red') +
  geom_vline(xintercept = Threshold3, linetype = 'dashed', color = 'red') +
  geom_vline(xintercept = Threshold2, linetype = 'dashed', color = 	'red') +
  geom_text(label = "5% HC: 95% LCL", color = 'red', x = Threshold3, y = 0)+
  geom_text(label = "5% hazard concentration", color = 'red', x = 110, y = 0.03)+
  geom_text(label = "5% HC: 95% UCL", color = 'red', x = Threshold2, y = 0)+
  geom_text(x = 110, y = 0, label = paste(Threshold1,"particles/L"), color = 'red') +  #label for hazard conc
  #geom_hline(yintercept = 0.925, linetype = 'twodash', color = "#A2A475") +
  #geom_text(label = "92.5% samples below 5% HC Mean", x = 4.5, y = 0.94, color = "#A2A475") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 12),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))
ECDF_model_occurrence_ADAM_white

```

```{r}
#dark mode
ECDF_model_occurrence_ADAM_dark <- ECDF_model_occurrence_ADAM +
  geom_vline(xintercept = Threshold1, linetype = 'dashed', color = 'red') +
  geom_vline(xintercept = Threshold3, linetype = 'dashed', color = 'red') +
  geom_vline(xintercept = Threshold2, linetype = 'dashed', color = 	'red') +
  geom_text(label = "95% LCL", color = 'red', x = Threshold3, y = 0, size = 5)+
  geom_text(label = "5% HC", color = 'red', x = Threshold1, y = 0, size = 5)+
  geom_text(label = "95% UCL", color = 'red', x = Threshold2, y = 0, size = 5)+
  geom_text(x = Threshold1, y = 0.1, label = paste(Threshold1,"particles/L"), color = 'red', size =5) +  #label for hazard conc
  #geom_hline(yintercept = 0.925, linetype = 'twodash', color = "yellow") +
  #geom_text(label = "92.5%", x = 3.0, y = 0.96, color = "yellow", size = 6) +
  dark_theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 12),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))
ECDF_model_occurrence_ADAM_dark
```




