---
title: 'Shiny App Manuscript Figures: Aquatic Organisms'
author: "Leah Thornton Hampton"
date: "4/26/2021"
output:
  html_document: 
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float: true
    code_folding: hide
---

# Data Import and Tidying

```{r Data Import and Packages, warning = FALSE, message = FALSE}

#Import packages
library(tidyverse) 
library(wesanderson)
library(pheatmap)
library(RColorBrewer)
library(ggpubr)
library(ssdtools)
library(scales)

library(ggdark)
library(ggsci)

#Import Data
aoc_setup <- readRDS("aoc_setup.RDS")
aoc_z <- readRDS("aoc_z.RDS")
```

# Figure 1

```{r}

#Select particle characteristics
selected_variables <- aoc_setup %>% 
  dplyr::select(
    size_f,
    shape_f,
    poly_f,
    density.reported.estimated,
    charge,
    functional.group,
    particle.behavior,
    weather.biofoul) %>% 
  filter(size_f != "Not Reported")

selected_variables$shape_f[selected_variables$shape_f == "Not Reported" ] <- NA
selected_variables$poly_f[selected_variables$poly_f == "Not Reported" ] <- NA
selected_variables$density.reported.estimated[selected_variables$density.reported.estimated == "estimated" ] <- NA
selected_variables$particle.behavior[selected_variables$particle.behavior == "Not Evaluated" ] <- NA
selected_variables$weather.biofoul[selected_variables$weather.biofoul == "N" ] <- NA
 
CompletenessSummary_size <- selected_variables %>%
  group_by(size_f) %>% 
  summarise_all((name = ~sum(is.na(.))/length(.))) %>% 
  mutate(across(is.numeric,~round(., 2))) %>% 
  mutate(across(is.numeric, ~100 *(1 -.))) %>% 
  rename("Size Category" = size_f, "Shape" = shape_f, "Polymer" = poly_f, "Density" = density.reported.estimated,
         "Charge" = charge, "Functional Group" = functional.group, "Particle Behavior" = particle.behavior,
         "Weathering" = weather.biofoul)  
  

#Heatmap

#Transpose data
transposed_size <- as.data.frame(t(as.matrix(CompletenessSummary_size[2:8]))) %>% #1 is category, 2-6 are variables
  arrange('1nm < 100nm')
#Reassign column names
colnames(transposed_size) <- c("1nm < 100nm", "100nm < 1µm", "1µm < 100µm", "100µm < 1mm", "1mm < 5mm")
#Format as matrix
MissingMatrix_size <- data.matrix(transposed_size)
#build heatmap
map <- pheatmap(MissingMatrix_size,
         main = "Particle Characteristics Reported", #title
         fontsize = 12,
         angle_col = 0,
         cluster_rows = FALSE, cluster_cols = FALSE,
         display_numbers = TRUE,
         fontsize_number = 12,
         number_color = "black",
         number_format = "%.0f%%",
         treeheight_row = 0, treeheight_col = 0, 
         color = c('#d73027','#fc8d59','#fee090','#e0f3f8','#91bfdb','#4575b4')) 

ggsave(filename = "Figure1.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = map, width = 8, height = 4, units = "in")
 
```

# Figure 2

```{r Leah, warning = FALSE, message = FALSE, fig.height = 7, fig.width = 12}

a <- aoc_setup %>%
  #Remove studies that don't report doses in mass OR counts per volume
  filter_at(vars(dose.mg.L.master, dose.particles.mL.master), any_vars(!is.na(.))) %>% 
  #Designate if doses were reported in mass, counts or both
  mutate(mass_count = ifelse(dose.mg.L.master.converted.reported == "reported" & dose.particles.mL.master.converted.reported == "converted", 1, 0)) %>%  
  mutate(particles_count = ifelse(dose.particles.mL.master.converted.reported == "reported" & dose.mg.L.master.converted.reported == "converted", 1, 0)) %>% 
  mutate(both_count = ifelse(dose.particles.mL.master.converted.reported == "reported" & dose.mg.L.master.converted.reported == "reported", 1, 0)) %>% 
  #Unique particles within each study
  distinct(doi, year, poly_f, shape_f, size.length.um.used.for.conversions, dose.mg.L.master.converted.reported, dose.particles.mL.master.converted.reported, mass_count, particles_count, both_count) %>%  
  #Remove letters from years if they exist
  mutate(year = str_remove(year,"[abc]")) %>% 
  #Count of the frequency of doses reported in mass, count or both within each year
  group_by(year) %>% 
  mutate(`Mass Only` = sum(mass_count, na.rm = TRUE)) %>% 
  mutate(`Particles Only` = sum(particles_count, na.rm = TRUE)) %>% 
  mutate(Both = sum(both_count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(year, Both, `Mass Only`, `Particles Only`) %>% 
  pivot_longer(!year, names_to = "dose_metric", values_to = "freq")

b <- a %>%
  ggplot(aes(x = year, y = freq, fill = fct_rev(dose_metric))) +
  geom_bar(position = "dodge", stat = "identity", color = "black") +
  theme_classic()+
  scale_fill_manual(values = c('#d73027','#fee090','#4575b4')) +
  scale_y_continuous(expand = c(0,0), limits = c(0,40)) +
  labs(y = "Number of Studies", x = "Year", fill = "Concentration Metric") +
  theme(text = element_text(size = 20), legend.position = "top")

ggsave(filename = "Figure2.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = b, width = 12, height = 8, units = "in")

```

# Polymer Type Percentages

```{r}

a <- aoc_setup %>% 
  group_by(doi, poly_f) %>% 
  summarise() %>%  
  ungroup() %>%
  group_by(poly_f) %>% 
  mutate(poly_count = n()) %>% 
  ungroup() %>%
  mutate(study_count = n_distinct(doi)) %>% 
  mutate(pct_poly = poly_count/study_count*100)

```

# Figure 3

```{r}

a <- aoc_setup %>% 
  filter(environment != "Terrestrial") %>% #drop terrestrial organisms
  filter(shape_f != "Not Reported") %>% #drop studies where shapes aren't reported
  filter(effect_f != "NA") %>% #drop ECX values
  filter(org_f %in% c("Crustacea", "Fish", "Mollusca")) %>%  #Select relevant organism groups
  filter(lvl2_f %in% c("Growth", "Body Condition", "Development", "Mortality", "Reproduction")) %>% 
  ggplot(aes(y = shape_f, x = dose.particles.mL.master, fill = effect_f)) +
  geom_boxplot(alpha = 0.8) +
  scale_x_log10() +
  labs(y = "Morphology", x = "Particles/mL", fill = "Effect") +
  theme_classic() +
  theme(text = element_text(size = 12))+
  scale_fill_manual(values = c("#fee090", '#4575b4'))

plot(a)

ggsave(filename = "Figure3.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = a, width = 8, height = 4, units = "in")

```

# Figure 4

```{r}

#Panel A (count)
a <- aoc_setup %>% 
  filter(environment != "Terrestrial") %>% #drop terrestrial organisms
  filter(size_f != "Not Reported") %>% #drop studies where shapes aren't reported
  filter(effect_f != "NA") %>% #drop ECX values
  drop_na(dose.mg.L.master|dose.particles.mL.master) %>%
  ggplot(aes(y = size_f, x = dose.particles.mL.master, fill = effect_f)) +
  geom_boxplot(alpha = 0.8) +
  scale_x_log10() +
  labs(y = "Size Category", x = "Particles/mL", fill = "Effect") +
  theme_classic() +
  theme(text = element_text(size = 12))+
  scale_fill_manual(values = c("#fee090", '#4575b4'))

plot(a)

#Panel B (mass)
b <- aoc_setup %>% 
  filter(environment != "Terrestrial") %>% #drop terrestrial organisms
  filter(size_f != "Not Reported") %>% #drop studies where shapes aren't reported
  filter(effect_f != "NA") %>% #drop ECX values
  drop_na(dose.mg.L.master|dose.particles.mL.master) %>%
  ggplot(aes(y = size_f, x = dose.mg.L.master, fill = effect_f)) +
  geom_boxplot(alpha = 0.8) +
  scale_x_log10() +
  labs(y = "Size Category", x = "µg/mL", fill = "Effect") +
  theme_classic() +
  theme(text = element_text(size = 12))+
  scale_fill_manual(values = c("#fee090", '#4575b4'))

plot(b)

ab <- ggarrange(a,b, nrow = 2, common.legend = TRUE, legend = "right", labels = "AUTO")

plot(ab)

ggsave(filename = "Figure4.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = ab, width = 8, height = 8, units = "in")

#Alternate Option(facet wrap)
# c <- aoc_setup %>% 
#   filter(environment != "Terrestrial") %>% #drop terrestrial organisms
#   filter(size_f != "Not Reported") %>% #drop studies where shapes aren't reported
#   filter(effect_f != "NA") %>% #drop ECX values
#   select(size_f, effect_f, dose.particles.mL.master, dose.mg.L.master) %>% 
#   drop_na(dose.mg.L.master|dose.particles.mL.master) %>% 
#   pivot_longer(cols = c(dose.particles.mL.master, dose.mg.L.master), names_to = "dose_metric", values_to = "dose") %>%   
#   mutate(dose_metric = factor(case_when(
#     dose_metric == "dose.particles.mL.master" ~ "particles/mL",
#     dose_metric == "dose.mg.L.master" ~ "µg/mL"))) %>% 
#   ggplot(aes(y = size_f, x = dose, fill = effect_f)) +
#   geom_boxplot(alpha = 0.8) +
#   scale_x_log10() +
#   facet_wrap(~dose_metric, scales = "free_x", nrow = 2) +
#   labs(y = "Size Category", x = "Dose", fill = "Effect") +
#   theme_classic() +
#   theme(text = element_text(size = 12))+
#   scale_fill_manual(values = c("#3B9AB2", "#EBCC2A"))
# 
# plot(c)
# 
# ggsave(filename = "Figure4_Alt.jpg",
#        path = "App_Nonessential/TeamX_Manuscript_Figures/",
#        plot = c, width = 8, height = 8, units = "in")

```

#Figure 5

```{r ERM}
###define sizes for filtering and alignment##
# smaller size bin
small_tier_lower_size <- 1 #um
small_tier_upper_size <- 5000 #um
upper.tissue.trans.size.um <- 100 #10 #um #set size for filtering data and x2M
# larger size bin
large_tier_lower_size <- 1 #um
large_tier_upper_size <- 5000 #um
```

```{r}
## First filter data with global filters
aoc_intermediate <- aoc_z %>% 
  filter(!environment %in% c("Terrestrial", "Not Reported"),
         org_f != "Bacterium",
         org_f != "Plant",
         effect.metric != "HONEC",
         tier_zero_tech_f == "Red Criteria Passed",
         risk.13 != 0 #Drop studies that received a score of 0 for endpoints criteria (this also drops studies that have not yet been scored) - KEEP THIS AFTER THE RED CRITERIA FILTERS  
         ) %>%  
  mutate(max.size.ingest.um = 1000 * max.size.ingest.mm)
```

## Count

```{r size category selection}
#1 - 100 nanometers
tier1_2_nano <- aoc_intermediate %>% 
         mutate(dose_new = dose.particles.mL.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 0.001, 0.1)) 

### 100 - 1000 nm
tier1_2_sub <- aoc_intermediate %>% 
         mutate(dose_new = dose.particles.mL.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 0.1, 1)) 

### 1 - 100 um
tier1_2_small <- aoc_intermediate %>% 
         mutate(dose_new = dose.particles.mL.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 1, 100)) 

### 100 - 1000 um
tier1_2_large <- aoc_intermediate %>% 
         mutate(dose_new = dose.particles.mL.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 100, 1000)) 
```

```{r data collapse}

#1 - 100 nanometers
tier1_2_nano_1q <- tier1_2_nano %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 100 - 1000 nm
tier1_2_sub_1q <- tier1_2_sub %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 1 - 100 um
tier1_2_small_1q <- tier1_2_small %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 100 - 1000 um
tier1_2_large_1q <- tier1_2_large %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))
```

### SSD Build

#### Nano
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_nano_1q <- ssd_fit_dists(tier1_2_nano_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_nano_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_nano_1q <- as.data.frame(ssd_gof(dists_tier1_2_nano_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_nano_1q <- predict(dists_tier1_2_nano_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_nano_1q <- tier1_2_nano_1q[order(tier1_2_nano_1q$Conc), ]
SSD_tier1_2_nano_1q$frac <- ppoints(tier1_2_nano_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_nano_1q_nano <- pred_tier1_2_nano_1q
SSD_tier1_2_nano_1q_nano <- SSD_tier1_2_nano_1q

tier1_2_nano_1q_lcl <- c(pred_tier1_2_nano_1q$lcl[5]) #CI95
tier1_2_nano_1q_hc5 <- c(pred_tier1_2_nano_1q$est[5]) #HC5
pred_tier1_2_nano_1q$est_format <-format(pred_tier1_2_nano_1q$est, digits = 3, scientific = TRUE)
```

#### Sub
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_sub_1q <- ssd_fit_dists(tier1_2_sub_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_sub_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_sub_1q <- as.data.frame(ssd_gof(dists_tier1_2_sub_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_sub_1q <- predict(dists_tier1_2_sub_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_sub_1q <- tier1_2_sub_1q[order(tier1_2_sub_1q$Conc), ]
SSD_tier1_2_sub_1q$frac <- ppoints(tier1_2_sub_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_sub_1q_sub <- pred_tier1_2_sub_1q
SSD_tier1_2_sub_1q_sub <- SSD_tier1_2_sub_1q

tier1_2_sub_1q_lcl <- c(pred_tier1_2_sub_1q$lcl[5]) #CI95
tier1_2_sub_1q_hc5 <- c(pred_tier1_2_sub_1q$est[5]) #HC5
pred_tier1_2_sub_1q$est_format <-format(pred_tier1_2_sub_1q$est, digits = 3, scientific = TRUE)
```

#### Small
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_small_1q <- ssd_fit_dists(tier1_2_small_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_small_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_small_1q <- as.data.frame(ssd_gof(dists_tier1_2_small_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_small_1q <- predict(dists_tier1_2_small_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_small_1q <- tier1_2_small_1q[order(tier1_2_small_1q$Conc), ]
SSD_tier1_2_small_1q$frac <- ppoints(tier1_2_small_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_small_1q_small <- pred_tier1_2_small_1q
SSD_tier1_2_small_1q_small <- SSD_tier1_2_small_1q

tier1_2_small_1q_lcl <- c(pred_tier1_2_small_1q$lcl[5]) #CI95
tier1_2_small_1q_hc5 <- c(pred_tier1_2_small_1q$est[5]) #HC5
pred_tier1_2_small_1q$est_format <-format(pred_tier1_2_small_1q$est, digits = 3, scientific = TRUE)
```

#### Large
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_large_1q <- ssd_fit_dists(tier1_2_large_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_large_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_large_1q <- as.data.frame(ssd_gof(dists_tier1_2_large_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_large_1q <- predict(dists_tier1_2_large_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_large_1q <- tier1_2_large_1q[order(tier1_2_large_1q$Conc), ]
SSD_tier1_2_large_1q$frac <- ppoints(tier1_2_large_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_large_1q_large <- pred_tier1_2_large_1q
SSD_tier1_2_large_1q_large <- SSD_tier1_2_large_1q

tier1_2_large_1q_lcl <- c(pred_tier1_2_large_1q$lcl[5]) #CI95
tier1_2_large_1q_hc5 <- c(pred_tier1_2_large_1q$est[5]) #HC5
pred_tier1_2_large_1q$est_format <-format(pred_tier1_2_large_1q$est, digits = 3, scientific = TRUE)
```

```{r}
# Build dataframe with all SSDs so we can get a color scale
p_t1_l_p <- pred_tier1_2_nano_1q_nano %>% mutate(size = "0.001 - 0.1 µm")
p_t1_l_u <- pred_tier1_2_sub_1q_sub %>% mutate(size = "0.1 - 1 µm")
p_t1_l_v <- pred_tier1_2_small_1q_small %>% mutate(size = "1 - 100 µm")
p_t1_l_sa <- pred_tier1_2_large_1q_large %>% mutate(size = "100 - 1,000 µm")

predictions_t1_large <- rbind.data.frame(p_t1_l_p, 
                                p_t1_l_u,
                                p_t1_l_v,
                                p_t1_l_sa) %>% 
  mutate(size = factor(size))
predictions_t1_large

#do the same for individual points
s_t1_l_p <- SSD_tier1_2_nano_1q_nano %>% mutate(size = "0.001 - 0.1 µm")
s_t1_l_u <- SSD_tier1_2_sub_1q_sub %>% mutate(size = "0.1 - 1 µm")
s_t1_l_v <- SSD_tier1_2_small_1q_small %>% mutate(size = "1 - 100 µm")
s_t1_l_sa <- SSD_tier1_2_large_1q_large %>% mutate(size = "100 - 1,000 µm")

points_t1_large <- rbind.data.frame(s_t1_l_p, 
                                s_t1_l_u,
                                s_t1_l_v,
                                s_t1_l_sa)

points_t1_large$size <- as.factor(points_t1_large$size)
```
#### Plot
```{r}

count_plot <- predictions_t1_large %>% 
ggplot(aes(x = est, y = percent/100, color = size)) +
  geom_line(size = 1) +
  geom_xribbon(aes(xmin = lcl, xmax = ucl, y = percent/100, fill = size),color = "black", alpha = 0.15) +
  geom_point(data = points_t1_large,aes(x = Conc, y =frac, color = size)) + 
  # scale_color_tron(name = "Size Bins") +
  scale_fill_manual(values = c('#d7191c','#fdae61','#abd9e9','#2c7bb6'),name = "Size Bins") +
  scale_color_manual(values = c('#d7191c','#fdae61','#abd9e9','#2c7bb6'),name = "Size Bins") +
  # scale_fill_tron(name = "Size Bins") +
  guides(fill = FALSE) + # suppress different legend for colors and lines
  coord_trans(x = "log10") +
      scale_x_continuous(limits = c(1e-5, 1e25),
                         breaks = scales::trans_breaks(
                           "log10", function(x) 10^x, n = 10),
                         labels = trans_format(
                           "log10", scales::math_format(10^.x))) +
  scale_y_continuous("Species Affected (%)", 
                     labels = scales::percent, 
                     limits = c(0,1)) +
  labs(x = "Particles/mL") +
  theme_classic()+
  theme(text = element_text(size = 12))

plot(count_plot)
```

## Mass

```{r size category selection}
#1 - 100 nanometers
tier1_2_nano <- aoc_intermediate %>% 
         mutate(dose_new = dose.mg.L.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 0.001, 0.1)) 

### 100 - 1000 nm
tier1_2_sub <- aoc_intermediate %>% 
         mutate(dose_new = dose.mg.L.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 0.1, 1)) 

### 1 - 100 um
tier1_2_small <- aoc_intermediate %>% 
         mutate(dose_new = dose.mg.L.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 1, 100)) 

### 100 - 1000 um
tier1_2_large <- aoc_intermediate %>% 
         mutate(dose_new = dose.mg.L.master / (af.time * af.noec)) %>%  
         drop_na(dose_new) %>% 
         mutate(dose_new = dose_new * 1000) %>% 
  filter(between(size.length.um.used.for.conversions, 100, 1000)) 
```

```{r data collapse}

#1 - 100 nanometers
tier1_2_nano_1q <- tier1_2_nano %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 100 - 1000 nm
tier1_2_sub_1q <- tier1_2_sub %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 1 - 100 um
tier1_2_small_1q <- tier1_2_small %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))

### 100 - 1000 um
tier1_2_large_1q <- tier1_2_large %>% 
  group_by(Species, Group) %>% 
  summarize(Conc = quantile(dose_new, 0.25))
```

### SSD Build

#### Nano
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_nano_1q <- ssd_fit_dists(tier1_2_nano_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_nano_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_nano_1q <- as.data.frame(ssd_gof(dists_tier1_2_nano_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_nano_1q <- predict(dists_tier1_2_nano_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_nano_1q <- tier1_2_nano_1q[order(tier1_2_nano_1q$Conc), ]
SSD_tier1_2_nano_1q$frac <- ppoints(tier1_2_nano_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_nano_1q_nano <- pred_tier1_2_nano_1q
SSD_tier1_2_nano_1q_nano <- SSD_tier1_2_nano_1q

tier1_2_nano_1q_lcl <- c(pred_tier1_2_nano_1q$lcl[5]) #CI95
tier1_2_nano_1q_hc5 <- c(pred_tier1_2_nano_1q$est[5]) #HC5
pred_tier1_2_nano_1q$est_format <-format(pred_tier1_2_nano_1q$est, digits = 3, scientific = TRUE)
```

#### Sub
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_sub_1q <- ssd_fit_dists(tier1_2_sub_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_sub_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_sub_1q <- as.data.frame(ssd_gof(dists_tier1_2_sub_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_sub_1q <- predict(dists_tier1_2_sub_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_sub_1q <- tier1_2_sub_1q[order(tier1_2_sub_1q$Conc), ]
SSD_tier1_2_sub_1q$frac <- ppoints(tier1_2_sub_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_sub_1q_sub <- pred_tier1_2_sub_1q
SSD_tier1_2_sub_1q_sub <- SSD_tier1_2_sub_1q

tier1_2_sub_1q_lcl <- c(pred_tier1_2_sub_1q$lcl[5]) #CI95
tier1_2_sub_1q_hc5 <- c(pred_tier1_2_sub_1q$est[5]) #HC5
pred_tier1_2_sub_1q$est_format <-format(pred_tier1_2_sub_1q$est, digits = 3, scientific = TRUE)
```

#### Small
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_small_1q <- ssd_fit_dists(tier1_2_small_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_small_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_small_1q <- as.data.frame(ssd_gof(dists_tier1_2_small_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_small_1q <- predict(dists_tier1_2_small_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_small_1q <- tier1_2_small_1q[order(tier1_2_small_1q$Conc), ]
SSD_tier1_2_small_1q$frac <- ppoints(tier1_2_small_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_small_1q_small <- pred_tier1_2_small_1q
SSD_tier1_2_small_1q_small <- SSD_tier1_2_small_1q

tier1_2_small_1q_lcl <- c(pred_tier1_2_small_1q$lcl[5]) #CI95
tier1_2_small_1q_hc5 <- c(pred_tier1_2_small_1q$est[5]) #HC5
pred_tier1_2_small_1q$est_format <-format(pred_tier1_2_small_1q$est, digits = 3, scientific = TRUE)
```

#### Large
```{r include=TRUE, warning=FALSE}
###### --modelling ####
dists_tier1_2_large_1q <- ssd_fit_dists(tier1_2_large_1q, left = "Conc", dists = c("weibull", "llogis", "lnorm", "gamma", "lgumbel"), computable = FALSE, silent = FALSE) 

#autoplot(dists_tier1_2_large_1q) #plots the distribution in ggplotier2
#### Goodness of fit ####
gof_tier1_2_large_1q <- as.data.frame(ssd_gof(dists_tier1_2_large_1q)) %>% mutate_if(is.numeric, ~ signif(., 3))

#### Prediction ####
set.seed(99)
pred_tier1_2_large_1q <- predict(dists_tier1_2_large_1q, average = TRUE, ic = "aicc", nboot = 10, ci= TRUE) 

#order data
SSD_tier1_2_large_1q <- tier1_2_large_1q[order(tier1_2_large_1q$Conc), ]
SSD_tier1_2_large_1q$frac <- ppoints(tier1_2_large_1q$Conc, 0.5)

#add unique ID for multiplot
pred_tier1_2_large_1q_large <- pred_tier1_2_large_1q
SSD_tier1_2_large_1q_large <- SSD_tier1_2_large_1q

tier1_2_large_1q_lcl <- c(pred_tier1_2_large_1q$lcl[5]) #CI95
tier1_2_large_1q_hc5 <- c(pred_tier1_2_large_1q$est[5]) #HC5
pred_tier1_2_large_1q$est_format <-format(pred_tier1_2_large_1q$est, digits = 3, scientific = TRUE)
```

```{r}
# Build dataframe with all SSDs so we can get a color scale
p_t1_l_p <- pred_tier1_2_nano_1q_nano %>% mutate(size = "0.001 - 0.1 µm")
p_t1_l_u <- pred_tier1_2_sub_1q_sub %>% mutate(size = "0.1 - 1 µm")
p_t1_l_v <- pred_tier1_2_small_1q_small %>% mutate(size = "1 - 100 µm")
p_t1_l_sa <- pred_tier1_2_large_1q_large %>% mutate(size = "100 - 1,000 µm")

predictions_t1_large <- rbind.data.frame(p_t1_l_p, 
                                p_t1_l_u,
                                p_t1_l_v,
                                p_t1_l_sa) %>% 
  mutate(size = factor(size))
predictions_t1_large

#do the same for individual points
s_t1_l_p <- SSD_tier1_2_nano_1q_nano %>% mutate(size = "0.001 - 0.1 µm")
s_t1_l_u <- SSD_tier1_2_sub_1q_sub %>% mutate(size = "0.1 - 1 µm")
s_t1_l_v <- SSD_tier1_2_small_1q_small %>% mutate(size = "1 - 100 µm")
s_t1_l_sa <- SSD_tier1_2_large_1q_large %>% mutate(size = "100 - 1,000 µm")

points_t1_large <- rbind.data.frame(s_t1_l_p, 
                                s_t1_l_u,
                                s_t1_l_v,
                                s_t1_l_sa)

points_t1_large$size <- as.factor(points_t1_large$size)
```
#### Plot
```{r}

mass_plot <- predictions_t1_large %>% 
ggplot(aes(x = est, y = percent/100, color = size)) +
  geom_line(size = 1) +
  geom_xribbon(aes(xmin = lcl, xmax = ucl, y = percent/100, fill = size),color = "black", alpha = 0.15) +
  geom_point(data = points_t1_large,aes(x = Conc, y =frac, color = size)) +
  scale_fill_manual(values = c('#d7191c','#fdae61','#abd9e9','#2c7bb6'),name = "Size Bins") +
  scale_color_manual(values = c('#d7191c','#fdae61','#abd9e9','#2c7bb6'),name = "Size Bins") +
  guides(fill = FALSE) + # suppress different legend for colors and lines
  coord_trans(x = "log10") +
      scale_x_continuous(limits = c(1e-15, 1e15),
                         breaks = scales::trans_breaks(
                           "log10", function(x) 10^x, n = 10),
                         labels = trans_format(
                           "log10", scales::math_format(10^.x))) +
  scale_y_continuous("Species Affected (%)", 
                     labels = scales::percent, 
                     limits = c(0,1)) +
  labs(x = "µg/mL") +
  theme_classic()+
  theme(text = element_text(size = 12))

plot(mass_plot)
```

## Combine Panels
```{r}

count_mass_ssd <- ggarrange(count_plot,mass_plot, nrow = 2, common.legend = TRUE, legend = "right", labels = "AUTO")

plot(count_mass_ssd)

ggsave(filename = "Figure5.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = count_mass_ssd, width = 8, height = 8, units = "in")

```

#Figure 7

```{r}

Group_size <- aoc_setup %>% 
  ggplot(aes(x = size.length.um.used.for.conversions, fill = org_f)) +
  geom_histogram(bins = 20, color = "black") +
  scale_fill_manual(values = c('#a50026','#d73027','#f46d43','#fdae61','#fee090','#ffffbf','#e0f3f8','#abd9e9','#74add1','#4575b4','#313695', '#641e16')) +
  ylab("Number of Observations")+
  xlab("Particle Length (µm)") +
  theme_classic() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(margin = margin(t = 10))) +
  scale_x_log10(labels = scales::label_number(accuracy = 1))+
  annotation_logticks(sides = "b", outside = TRUE)+
  coord_cartesian(clip = "off")+
  scale_y_continuous(expand = c(0,0))+
  labs(fill = "Organism Group")

plot(Group_size)

Endpoint_size <- aoc_setup %>% 
  ggplot(aes(x = size.length.um.used.for.conversions, fill = lvl1_f)) +
  geom_histogram(bins = 20, color = "black") +
  scale_fill_manual(values = c('#d73027','#f46d43','#fdae61','#fee090','#ffffbf','#e0f3f8','#abd9e9','#74add1','#4575b4')) +
  xlab("Particle Length (µm)") +
  ylab("Number of Observations")+
  theme_classic() +
  theme(text = element_text(size = 12),
        axis.text.x = element_text(margin = margin(t = 10))) +
  scale_x_log10(labels = scales::label_number(accuracy = 1))+
  annotation_logticks(sides = "b", outside = TRUE)+
  coord_cartesian(clip = "off")+
  scale_y_continuous(expand = c(0,0))+
  labs(fill = "Endpoint Category")

plot(Endpoint_size)

size_group_endpoint <- ggarrange(Group_size,Endpoint_size, nrow = 2, legend = "right", labels = "AUTO")

plot(size_group_endpoint)

ggsave(filename = "Figure7.jpg",
       path = "App_Nonessential/TeamX_Manuscript_Figures/",
       plot = size_group_endpoint, width = 8, height = 8, units = "in")

```

